WITH SELECT_USER AS (
SELECT USER_ID
FROM USER_INFO
WHERE JOINED LIKE '2021%')

SELECT YEAR(SALES_DATE) AS YEAR, 
        MONTH(SALES_DATE) AS MONTH,
        COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
        ROUND(COUNT(DISTINCT OS.USER_ID) / (SELECT COUNT(*)
                                            FROM SELECT_USER), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE OS
JOIN SELECT_USER SU
ON OS.USER_ID = SU.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
